#pragma once
#include <pch.h>
#include <arch/datatypes/type_sparseSet.h>
#include <arch/resources/res_shader.h>

namespace ShaderConstants {

	// - shader paths ---------------------------------------------------------
	inline constexpr const char* C_PATH_VERTEXSHADERPATH		{ "./Assets/Shaders/vtx_vertex.vert" };
	inline constexpr const char* C_PATH_LAMBERTFRAGSHADERPATH	{ "./Assets/Shaders/frag_lambert.frag" };
	inline constexpr const char* C_PATH_PHONGFRAGSHADERPATH		{ "./Assets/Shaders/frag_phong.frag" };
	// - shader identifiers ---------------------------------------------------
	inline constexpr const char* C_ID_VERTEXSHADER				{ "C_VERTEX_SHADER" };
	inline constexpr const char* C_ID_LAMBERTFRAGSHADER			{ "C_LAMBERTFRAG_SHADER" };
	// - shader Program 0000---------------------------------------------------
	inline constexpr const char* C_ID_LAMBERTSHADERPROG			{ "BRDF_LAMBERT" };
}

struct ShaderProgramDesc {
	std::string vertex;
	std::string fragment;
	std::optional<std::string> geometry;
	std::optional<std::string> tessControl;
	std::optional<std::string> tessEval;
	std::optional<std::string> compute;
};


using ShaderHandler = SparseSetView<Shader>;
using ShaderProgramHandler = SparseSetView<ShaderProgram>;

class ShaderManager {
public:
	void Init();
	void Cleanup();


	// shader
	GLuint AddShader(std::string _identifier, Shader _shader);
	void RemoveShader(std::string _identifier);
	void RemoveShader(GLuint _handle);
	
	GLuint CreateShader(std::string _identifier);

	SparseSetView<Shader> GetShader(GLuint _identifier);
	SparseSetView<const Shader> GetShader(GLuint _identifier) const;
	SparseSetView<Shader> GetShader(std::string _identifier);
	SparseSetView<const Shader> GetShader(std::string _identifier) const;

	// - program ------------------------------------------------------------
	GLuint AddShaderProgram(std::string _identifier, ShaderProgram _program);
	void RemoveShaderProgram(GLuint _handle);
	void RemoveShaderProgram(std::string _identifier);
	GLuint CreateShaderProgram(std::string _identifier);


	SparseSetView<ShaderProgram> GetShaderProgram(std::string _identifier);
	SparseSetView<const ShaderProgram> GetShaderProgram(std::string _identifier) const;
	SparseSetView<ShaderProgram> GetShaderProgram(GLuint _handle);
	SparseSetView<const ShaderProgram> GetShaderProgram(GLuint _handle) const;


	// - database -----------------------------------------------------------
	SparseSet<GLuint, ShaderProgram>& GetShaderProgramDatabase();
	const SparseSet<GLuint, ShaderProgram>& GetShaderProgramDatabase() const;

	SparseSet<GLuint, Shader>& GetShaderDatabase();
	const SparseSet<GLuint, Shader>& GetShaderDatabase() const;

private:
	GLuint GetNewShaderID();
	GLuint GetNewShaderProgramID();

	void ReclaimShaderID(GLuint _id);
	void ReclaimShaderProgramID(GLuint _id);

private:
	// note - handle is made here, id is generated by program.
	SparseSet<GLuint, Shader> m_shaderDatabase;
	std::unordered_map<std::string, GLuint> m_shaderAliasLookup;

	SparseSet<GLuint, ShaderProgram> m_shaderProgramDatabase;
	std::unordered_map<std::string, GLuint> m_shaderProgramAliasLookup;


	// - ids ----------------------------------------------------------------
	GLuint m_shaderCounter			{};
	std::queue<GLuint> m_shaderCounterFree;

	size_t m_shaderProgramCounter	{};
	std::queue<GLuint> m_shaderProgramCounterFree;

};